#spring:
#  datasource:
#    url: jdbc:sqlserver://bookauthor.database.windows.net:1433;database=bookapp;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: Sandeep
#    password: Sunny@1999
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
#
#server:
#  port: 9191